# Generated by Django 4.2.6 on 2023-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLmanagement', '0002_user_cancreateauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
